.TH "TMEX" "1" "June 2024"
.SH "NAME"
\fBtmex – “tmux-execute” – a lightweight tmux command & layout composer\fR
.SH DESCRIPTION
.br
Basic usage:
.RS 2
.nf
tmex your\-session\-name "cmd a" "cmd b" "cmd c" \.\.\. etc\.
.fi
.RE
.P
With options and custom layout provided:
.RS 2
.nf
tmex your\-session\-name \-\-npm \-\-layout=1224 \-\-transpose "cmd a" "cmd b" "cmd c" \.\.\. etc\.
.fi
.RE
.P
Shorthand:
.RS 2
.nf
tmex your\-session\-name \-nt 1224 "cmd a" "cmd b" "cmd c" \.\.\. etc\.
                        │     │              │
              options ──┘     └── layout     └── shell commands
.fi
.RE
.P
Session name optional if \fB\-\-npm\fP or \fB\-n\fP is set :
.RS 2
.nf
tmex \-nt 1224 "cmd a" "cmd b" "cmd c" \.\.\. etc\.
.fi
.RE
.P
Full options list (also accessible via \fBtmex \-h\fP):
.RS 2
.nf
tmex <session\-name> ··············  session name required unless \-\-npm or \-\-kill set; all other args optional
  [\-h|\-\-help]       [\-v|\-\-version]
  [\-l|\-\-layout]  0\-9 [ ] { } \. \- +  layout string, each digit represents number of panes in column
  [\-f|\-\-focus]   0\-9 ·············  tmux pane to select by index, must be an integer, positive or negative
  [\-w|\-\-window] "name" ···········  separate sets of tmex args to start session with multiple tmux windows
  [\-W|\-\-window\-focus] "name" ·····  same as above, but focus this window when session begins
  [\-t|\-\-transpose] ···············  build layout in left\-to\-right orientation instead of top\-to\-bottom
  [\-n|\-\-npm] ·····················  if set, prefix each command with "npm run" for package\.json scripts
  [\-p|\-\-print] ···················  emit command as string of tmux args instead of invoking tmux directly
  [\-d|\-\-detached] ················  invoke tmux with \-d ; useful for piping data to tmex
  [\-r|\-\-reattach] ················  if tmux session already exists, re\-attach to it instead of replacing it
  [\-s|\-\-shellless] ···············  if set, invoke commands directly with tmux instead of running inside shell
  [\-k|\-\-kill] ····················  kill the current or specified tmux session 
  [\-c|\-\-command] "new\-session" ···  tmux command that will be called with constructed arguments; default is "new\-session"
  ["command 1" "command 2" \.\.\.] ··  shell commands to be executed in each pane 
.fi
.RE
.SH Layout
.P
If no layout is provided, a sensible default will be generated to match the number of commands provided\. However, layouts are fully customizable via \fB\-\-layout\fP or \fB\-l\fP :
.RS 2
.nf
tmex your\-session\-name 1224
# or
tmex your\-session\-name \-l 1224
# or
tmex your\-session\-name \-\-layout=1224
>>>                             │
   1─────2─────2─────4──────────┘
┌─────┬─────┬─────┬─────┐
│     │     │     │  f  │
│     │  b  │  d  ├─────┤
│     │     │     │  g  │
│  a  ├─────┼─────┼─────┤
│     │     │     │  h  │
│     │  c  │  e  ├─────┤
│     │     │     │  i  │
└─────┴─────┴─────┴─────┘
.fi
.RE
.P
Each digit of \fB1224\fP specifies the number of panes each column will be split into\. To operate on rows instead of columns, transpose layout left\-to\-right instead of top\-to\-bottom with \fB\-\-transpose\fP or \fB\-t\fP:
.RS 2
.nf
tmex your\-session\-name \-\-transpose \-\-layout=1224
>>>                                         │
┌───────────────────────┐                   │
│           a           │ 1─────────────────┘
├───────────┬───────────┤ │
│     b     │     c     │ 2
├───────────┼───────────┤ │
│     d     │     e     │ 2
├─────┬─────┼─────┬─────┤ │
│  f  │  g  │  h  │  i  │ 4
└─────┴─────┴─────┴─────┘
.fi
.RE
.P
Layouts may be arbitrarily complex via sublayouts \fB[xyz]\fP and custom sizing \fB{xyz}\fP:
.RS 2
.nf
tmex your\-session\-name \-\-layout=1[2{13}1]4{4112}
>>>                                 │      │
           ┌────────────────────────┘      │
┌───────┬──│────┬───────┐                  │
│       │  │    │       │                  │
│       │ 1│3   │   4──────────────────────┘
│       │  │    │   │   │
│       ├──┴────┼───1───┤
│       │       ├───1───┤
│       │       ├───│───┤
│       │       │   2   │
└───────┴───────┴───────┘
.fi
.RE
.P
In the example above, the layout \fB1[2{13}1]4{4112}\fP contains the sublayout \fB[2{13}1]\fP which is constructed in the second column of the full layout\. This in turn specifies relative sizing \fB2{13}\fP for its first 2 panes, meaning the 2nd pane will be 3x the size of the 1st \. The 3rd column of the full layout \fB4{4112}\fP also defines custom sizing of panes \.
.P
If you want to change the widths of columns at the top level of the layout, you'll need to prefix the layout with a set of widths:
.RS 2
.nf
tmex your\-session\-name \-\-layout={152}1[2{13}1]4{4112}
>>>
├─1─┼───────5───────┼──2───┤
┌───┬────┬──────────┬──────┐
│   │    │          │      │
│   │  1 │    3     │  4   │
│   │    │          │      │
│   ├────┴──────────┼──1───┤
│   │               ├──1───┤
│   │               ├──────┤
│   │               │  2   │
└───┴───────────────┴──────┘
.fi
.RE
.P
Note that the sublayout \fB[2{13}1]\fP is treated as a single column when sizing is applied, so that set of panes as a whole receives \fB5\fP as its width relative to the other columns\.
.SH Top\-level layout sizing 
.P
Since a sizing clause like \fB{123}\fP always \fIfollows\fR a pane count number within a layout, you may be wondering how sizing could be applied to the "top level" columns  of a layout\. For example, given the layout \fB234\fP, how could you:

.RS 1
.IP \(bu 2
make the first column \fB2\fP fill half the screen
.IP \(bu 2
make the second column \fB3\fP fill a third of the screen
.IP \(bu 2
make the third column \fB4\fP fill the remainder  of the screen

.RE
.P
This special case is handled by placing the sizing clause at the \fIstart\fR of the layout :
.RS 2
.nf
tmex your\-session\-name \-\-layout={321}234
>>>
┌───────────────┬──────────┬─────┐
│               │          │  4  │
│               │    3     │     │
│       2       │          ├─────┤
│               ├──────────┤  4  │
│               │          │     │
├───────────────┤    3     ├─────┤
│               │          │  4  │
│               ├──────────┤     │
│       2       │          ├─────┤
│               │    3     │  4  │
│               │          │     │
└───────────────┴──────────┴─────┘
.fi
.RE
.P
\fBNOTE:\fR The same can be accomplished \fIwithout\fR special casing, using sub\-layouts and the transposition feature:
.RS 2
.nf
tmex your\-session\-name \-\-transpose \-\-layout=[234]{321}    # equivalent to \-\-layout={321}234 above
tmex your\-session\-name \-\-layout=[[234]{321}]              # also equivalent
.fi
.RE
.P
These may be functionally equivalent, but they're a far cry from intuitive! Feel free to use whichever of the three forms makes the most logical sense to you though\.
.SH Grid sub\-layouts 
.P
Sometimes you might want a row/column of your layout to contain a grid of N panes, laid out using the default algorithm\. This is done by placing \fB{+}\fP \fIafter\fR a number of panes in the layout\. This can be thought of as "requesting a grid layout" for the preceeding number of panes – \fB+\fP is a visual mnemonic in that it separates the space within \fB{ }\fP in a grid\-like formation\.
.RS 2
.nf
tmex your\-session\-name \-\-layout=35{+}4
>>>
┌─────┬─────┬─────┬─────┬─────┐
│     │     │     │     │  4  │
│  3  │     │     │     │     │
│     │     │  5  │  5  ├─────┤
├─────┤     │     │     │  4  │
│     │     │     │     │     │
│  3  │  5  ├─────┼─────┼─────┤
│     │     │     │     │  4  │
├─────┤     │     │     │     │
│     │     │  5  │  5  ├─────┤
│  3  │     │     │     │  4  │
│     │     │     │     │     │
└─────┴─────┴─────┴─────┴─────┘
.fi
.RE
.P
The layout above is equivalent to:
.RS 2
.nf
tmex your\-session\-name \-\-layout=31224
.fi
.RE
.P
because \fB5{+}\fP is expanded to \fB122\fP, which is the default grid layout when 5 panes are required\. You can experiment with commands such as \fBtmex your\-session\-name \-\-layout=7{+}\fP to see what default grid layout is produced for each number of panes\. In general, each default grid layout attempts to equalize pane sizes, widths, and heights as much as possible, keeping the largest pane on the left with odd numbers of panes\.
.SH Multi\-digit pane counts 
.P
For any of the layouts above, pane counts 10 and greater can be achieved by separating digits with \fB\|\.\fP characters\. For example:
.RS 2
.nf
tmex your\-session\-name \-\-layout=8\.10\.12
.fi
.RE
.P
will produce a layout of 3 columns, the first with 8 panes, the second with 10 panes, and the third with 12 panes\.
.P
These layouts are equivalent (the \fB\|\.\fP characters have no effect when used with single\-digit pane counts):
.RS 2
.nf
tmex your\-session\-name \-\-layout=1234
tmex your\-session\-name \-\-layout=1\.2\.3\.4
.fi
.RE
.P
To understand whether a set of numeric characters will be treated as one multi\-digit number, or a series of single\-digit numbers, simply ask \fIIs this set of numeric characters adjacent to a \fB\|\.\fP character?\fR If so, they are multi\-digit numbers; otherwise they are single\-digit numbers\.
.P
This general rule will help explain this more convoluted  layout:
.RS 2
.nf
tmex your\-session\-name \-\-layout=11\.[23]45[6\.7]8\.
#                  multi\-digit\-\-^^  ^^|^^ ^|^ ^\-\-multi\-digit
#                                     |    |
#                          single\-digit    multi\-digit
.fi
.RE
.P
\fB11\.\fP is treated as multi\-digit, and produces a column 11 panes\. \fB23\fP are treated as a sublayout of single\-digit pane counts, producing 5 panes total\. \fB45\fP have no adjacent \fB\|\.\fP characters so they produce columns of 4 and 5 panes\. \fB6\.7\fP are treated as multi\-digit, but still produce separate rows  of 6 and 7 panes respectively – the \fB\|\.\fP has no effect\. Finally, \fB8\.\fP is treated as multi\-digit due to the adjacent \fB\|\.\fP but still produces a column of 8 panes – the \fB\|\.\fP has no effect)\.
.SH Focused Pane Control 
.P
There are a few different ways to select a specific pane to be "focused" – with cursor active inside it – when your layout is initialized\.
.RS 2
.nf
tmex your\-session\-name \-\-layout=135+7
# the above will focus the first pane of the third column of your layout
tmex your\-session\-name \-\-layout=135++7
# the above will focus the second pane of the third column of your layout
tmex your\-session\-name \-\-layout=135\-7
# the above will focus the last pane of the third column of your layout
tmex your\-session\-name \-\-layout=135\-\-\-7
# the above will focus the third\-to\-last pane of the third column of your layout
.fi
.RE
.P
The above commands focus panes relative to the column they reside in\. You can also select a pane to be focused relative to the entire sequence of panes in the layout:
.RS 2
.nf
tmex your\-session\-name \-\-layout=1357 \-\-focus=4
# the above will focus the first pane of the third column of your layout
# this happens to be equivalent to \-\-layout=135+7 from above
tmex your\-session\-name \-\-layout=1357 \-f=5      # shorthand argument
# the above will focus the second pane of the third column of your layout
# this happens to be equivalent to \-\-layout=135++7 from above
tmex your\-session\-name \-f=\-8 1357              # shorthand argument + shorthand layout
# the above will focus the last pane of the third column of your layout
# this happens to be equivalent to \-\-layout=135\-7 from above
tmex your\-session\-name \-f=\-10 1357             # shorthand argument + shorthand layout
# the above will focus the third\-to\-last pane of the third column of your layout
# this happens to be equivalent to \-\-layout=135\-\-\-7 from above
.fi
.RE
.SH Multi\-window management 
.P
You may want to create multiple tmux windows within your tmux session, and navigate between them using \fBCTRL+B→N\fR , \fBCTRL+B→P\fR , \fBCTRL+B→[0\-9]\fR \.
.P
For example, you might want one window called \fBabc\fP, with 6 panes laid out \fB123\fP, and a second window called \fBefg\fP with 8 panes laid out \fB44\fP\|\. To accomplish this, use the \fB\-\-window\fP or \fB\-w\fP option, which is unique in that it can be repeated any number of times within a tmex command:
.RS 2
.nf
tmex your\-session\-name \-\-window abc 123 \-w efg 44
.fi
.RE
.P
Every series of arguments after an instance of \fB\-\-window\fP or \fB\-w\fP is treated as an entirely separate tmex invocation, with separate arguments and commands list\. To pass some arguments to the command above  and provide some commands, you'd write:
.RS 2
.nf
tmex your\-session\-name \-w abc \-f4 123 "cmd a" "cmd b" \-w efg \-f\-2 44 "cmd c"
.fi
.RE
.P
By default, the session will begin with the \fIfirst\fR window in focus\. If you'd like to begin with a different window in focus, simply replace the corresponding \fB\-\-window\fP or \fB\-w\fP arg with \fB\-\-window\-active\fP or \fB\-W\fP, respectively:
.RS 2
.nf
tmex your\-session\-name \-\-window\-focus abc 123 \-w efg 44  # focus 1st window
tmex your\-session\-name \-\-window abc 123 \-W efg 44         # focus 2nd window
.fi
.RE
.P
You may be wondering what will happen if you put any args \fIbefore\fR the first \fB\-w\fP arg\. This will work fine; the command will still produce two windows and the preceeding args will simply be used against the first window:
.RS 2
.nf
tmex your\-session\-name \-l 123 \-f4 \-w abc "cmd a" "cmd b" \-w efg \-f\-2 44 "cmd c"
# equivalent to command directly above
.fi
.RE
.P
Each \fB\-\-window\fP or \fB\-w\fP argument should be directly followed by the intended name of the window, which will label it in tmux's bottom bar and aid navigation\. However, empty\-string \fB&#39;&#39;\fP provided as a name is entirely valid, and there's also a shorthand if you wish to omit a window's name (usually the shell name is used in its place, eg\. \fBbash\fP):
.RS 2
.nf
tmex your\-session\-name \-w\- 123 \-w\- 44  # produce nameless tmux windows
tmex your\-session\-name \-\-window \- 123 \-\-window \- 44       # equivalent
tmex your\-session\-name \-w '' 123 \-w '' 44                 # equivalent
tmex your\-session\-name \-\-window '' 123 \-\-window '' 44     # equivalent
.fi
.RE
.P
\fBNOTE\fR that \fB\-w&#39;&#39;\fP  does \fInot\fR work, since shell string concatenation causes this to be treated as simply \fB\-w\fP and the \fInext\fR arg will be inadvertently used as the window name\.
.P
\fBNOTE\fR that you must \fIalways\fR specify a top\-level session name when using multiple windows, even if \fB\-\-npm\fP / \fB\-n\fP is specified\. This is because npm\-mode will be applied on a per\-window basis, not to the session as a whole \-\- necessary if you want to run commands in \fIsome\fR windows as NPM scripts, but not commands in \fIall\fR windows\.
.SH Usage within tmux sessions 
.P
You can use tmex within an existing tmux session to split panes or create additional windows, using the full suite of layout features\. Usage within a tmux session will be automatically detected by tmex, and it will avoid spawning a nested tmux session\. You may omit session name from the tmex command in these cases :
.RS 2
.nf
# within a tmux session
tmex 123             # split current pane into a 123 layout
tmex \-w\- 123         # same as above, split current pane within current window
tmex \-w\- 123 \-w\- 44  # same as above, and also add a new window with 44 layout
.fi
.RE
.P
There's some possible ambiguity when invoking shell commands with nested tmex calls, since the first command may be treated as a session name and ignored\. To avoid this, use \fB\-\-\fP to explicitly stop argument parsing and treat all following arguments as shell commands:
.RS 2
.nf
# within a tmux session
tmex "cmd a" "cmd b" "cmd c"   # INCORRECT \- "cmd a" treated as session name and ignored
tmex \-\- "cmd a" "cmd b" "cmd c"  # CORRECT \- "cmd a" treated as shell command
.fi
.RE
.SH Kill command 
.P
You can kill a tmux session from anywhere using
.RS 2
.nf
tmex \-k your\-session\-name
tmex your\-session\-name \-k      # equivalent
tmex your\-session\-name \-\-kill  # equivalent
.fi
.RE
.P
If you're \fIinside\fR a tmux session at the moment, you can simply write
.RS 2
.nf
tmex \-k
.fi
.RE
.P
The session name will be inferred from current environment variables, and the session will be killed\.
.SH npm
.P
Simplify \fBpackage\.json\fP scripts via \fB\-\-npm\fP or \fB\-n\fP\|\. Commands will be prefixed with \fBnpm run\fP  and session name will default to \fB$npm_package_name\fP\|\. This will expand to match the \fBname\fP field set in \fBpackage\.json\fP\|\.
.P
\fBNOTE:\fR tmux replaces \fB\|\.\fP→\fB_\fP, \fB:\fP→\fB_\fP, \fB\\\fP→\fB\\\\\fP when setting session names, so your final session name may not exactly match the \fBname\fP specified in \fBpackage\.json\fP (or the name you provide via the \fB<session\-name>\fP argument at the command line)\.
.RS 2
.nf
cat package\.json | grep name
>>> "name": "special\-project"

tmex \-n watch server typecheck
>>>
┌───────────┬───────────┐
│ npm run   │ npm run   │
│ watch     │ server    │
│           ├───────────┤
│           │ npm run   │
│           │ typecheck │
└───────────┴───────────┘
session : special\-project
.fi
.RE
.SH Install
.P
Homebrew:
.RS 2
.nf
brew tap evnp/tmex && brew install tmex
.fi
.RE
.P
NPM:
.RS 2
.nf
npm install \-g tmex
.fi
.RE
.P
curl:
.RS 2
.nf
read \-rp $'\\n'"Current \\$PATH:"$'\\n'"${PATH//:/ : }"$'\\n\\n'"Enter a directory from the list above: " \\
  && curl \-L \-o "${REPLY/\\~/$HOME}/tmex" https://github\.com/evnp/tmex/raw/main/tmex \\
  && chmod +x "${REPLY/\\~/$HOME}/tmex"
.fi
.RE
.P
tmex has no external dependencies , but it's good practice to audit code before downloading onto your system to ensure it contains nothing unexpected\. Please view the full source code for tmex here: https://github.com/evnp/tmex/blob/master/tmex
.P
If you also want to install tmex's man page:
.RS 2
.nf
read \-rp $'\\n'"Current \\$MANPATH:"$'\\n'"${MANPATH//:/ : }"$'\\n\\n'"Enter a directory from the list above: " \\
  && curl \-L \-o "${REPLY/\\~/$HOME}/man1/tmex\.1" https://github\.com/evnp/tmex/raw/main/man/tmex\.1
.fi
.RE
.P
Verify installation:
.RS 2
.nf
tmex \-v
==> tmex 2\.0\.0

brew test tmex
==> Testing tmex
==> /opt/homebrew/Cellar/tmex/2\.0\.0/bin/tmex test \-\-print 1234 hello world
.fi
.RE
.P
If you see the output \fBWarning: tmux is not yet installed, tmex will not work without tmux\.\fP you'll need to install tmux as well\.
.RS 2
.nf
brew install tmux      # OSX 
sudo apt install tmux  # Ubuntu, Debian, etc\.
.fi
.RE
.P
or refer to https://github.com/tmux/tmux/wiki/Installing for install instructions applicable to your platform\.
.SH Tests
.P
Run once:
.RS 2
.nf
npm install
npm test
.fi
.RE
.P
Use \fBfswatch\fP to re\-run tests on file changes:
.RS 2
.nf
brew install fswatch
npm install
npm run testw
.fi
.RE
.P
Non\-OSX: replace \fBbrew install fswatch\fP with package manager of choice 
.SH License
.P
MIT

